### ISSUE TITLE
El cliente quiere pedir cita al médico a través del sistema

### ISSUE THREAD

**Issue by RubenDelgadoPareja** [RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica#1]
- El usuario debe estar registrado previamente
- El usuario podrá elegir la fecha de la cita (mientras haya hueco por prioridad)
- El usuario podrá cancelar la cita con 48 horas de antelación

**Comment by JJ** [comment]
No es una HU, porque no representa ningún beneficio para el usuario. Tampoco está relacionado con el triage inteligente, así que podría ser un issue, pero no tiene nada que ver con el tema, en principio.

**Comment by JJ** [comment]
Sigue con la etiqueta user-stories
