### ISSUE TITLE
Milestones del Triage Inteligente

### ISSUE THREAD

**Issue by RubenDelgadoPareja** [RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica#10]
El proyecto estará organizado mediante los hitos que se cumplirán después de completar una serie de PMVs, los cuales tendrán mayor complejidad y estarán enfocados al cliente 

* Crear todos los hitos y sus respectivos PMVs que vamos a tener que desarrollar para cumplir con la motivación y objetivo del proyecto

**Comment by JJ** [comment]
Recuerda que los issues son problemas. En este caso, "el proyecto tiene que estar organizado en una serie de PMVs de complejidad creciente y más acercados a los requisitos de la clientela". Las cosas no se hacen por hacer, se hacen por una razón y saber cuál es la razón ayuda a hacerlas correctamente.
Igual con el resto de los issues, revísalos.

**Comment by RubenDelgadoPareja** [comment]
Cerrada en el PR #23
