### ISSUE TITLE
Eliminar código desfasado y sin uso

### ISSUE THREAD

**Issue by RubenDelgadoPareja** [RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica#111]
Esta issue resuelve el problema de una mezcla que se hizo contra develop prematuramente. El código que se mergeó y está en desuso son un conjunto de clases abstractas para modelar los conceptos del Diseño Dirigido por le Dominio. El motivo para eliminar el código es que compe rompe con el paradigma YAGNI "You aren't gonna need it" , que es una de las buenas prácticas de la Programación Extrema

**Comment by JJ** [comment]
Recuerda que los issues son siempre problemas, no tareas. En este caso, deberías haber indicado qué hace un código desfasado y en qué casos no se usa. Indicar una solución de antemano previene el análisis del problema en profundidad, porque puede que parte de ese código se use, o alguno se pueda reutilizar.
En todo caso, un producto mínimamente viable puede incluir código obsoleto. No es algo que tengas que incluir en este milestone. Recuerda que en cada milestone siempre se busca el producto mínimamente viable.

**Comment by RubenDelgadoPareja** [comment]
> Recuerda que los issues son siempre problemas, no tareas. En este caso, deberías haber indicado qué hace un código desfasado y en qué casos no se usa. Indicar una solución de antemano previene el análisis del problema en profundidad, porque puede que parte de ese código se use, o alguno se pueda reutilizar. En todo caso, un producto mínimamente viable puede incluir código obsoleto. No es algo que tengas que incluir en este milestone. Recuerda que en cada milestone siempre se busca el producto mínimamente viable.

Actualizo el cuerpo de la issue explicando porqué está el código y porqué no se usa
