### ISSUE TITLE
Los objetivos deben ser medibles y siempre en el espacio del problema

### ISSUE THREAD

**Issue by JJ** [RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica#16]
Este  no es el objetivo, esto es lo que vas a hacer

https://github.com/RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica/blob/46dd0f061bcbb3d98ef853d9a642d17b7c0cbb65/doc/secciones/01_introduccion.tex#L19

Los objetivos son siempre resolver un problema y hacerlo de forma cuantificable. Por ejemplo, "acelerar el proceso de toma de decisiones en triage para poder procesar a más pacientes"

Tienes que relacionar también el problema con la motivación. ¿Hay muchos retrasos en atención por el triage? ¿Hay alguna otra razón? ¿Se puede resolver por medios informáticos? En todo caso, debes reformular los objetivos y poner lo que actualmente es un objetivo como posible solución al mismo.

**Comment by RubenDelgadoPareja** [comment]
Cerrada en el PR #15   y #24
