### ISSUE TITLE
Formular una relación clara con el problema y el diagnóstico del mismo

### ISSUE THREAD

**Issue by JJ** [RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica#17]
Tienes que relacionar la primera frase (problema con las consultas médicas) con la segunda (triage). ¿Las listas de espera se deben al triage?

https://github.com/RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica/blob/46dd0f061bcbb3d98ef853d9a642d17b7c0cbb65/doc/secciones/01_introduccion.tex#L9

También, por supuesto, tendrás que explicar qué es el triage para las personas que no sepan lo que es (que será todo el tribunal (y recuerda que el tribunal es cliente y tiene que tener su propia HU)

**Comment by RubenDelgadoPareja** [comment]
Cerrada en el PR #18
