### ISSUE TITLE
 Un cliente quiere hacer acceder al sistema 

### ISSUE THREAD

**Issue by RubenDelgadoPareja** [RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica#2]
- Incluimos en esta HU el cierre de sesión de un usuario

**Comment by JJ** [comment]
Esto es lo que tú quieres que haga el usuario, no lo que el usuario quiere. Si pones "ojalá que" delante de lo que hace una HU y no suena creíble, es que no es una HU.
