### ISSUE TITLE
Reorganiza los milestones y su contenido

### ISSUE THREAD

**Issue by JJ** [RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica#22]
Para empezar, si vas a incluir algo de texto en el informe durante el milestone 0, debes ponerlo también en el mismo; todos los entregables de cada milestone deben estar descritos explícitamente.

> Aunque implícitamente todo lo que se haga en cada milestone debe irse incluyendo sobre la marcha en el informe, porque es parte del PMV, si alguna cosa no está incluida (por ejemplo, los objetivos del trabajo en el milestone cero), hay que hacerlo.

Por otro lado, los milestones deben ser graduales, y no dar saltos de la infraestructura al primer prototipo. Es más, "primer prototipo" tampoco dice nada, hay que aclarar qué capas de abstracción van a irse incluyendo y en qué orden, empezando por un modelo del problema, a continuación las diferentes partes de la lógica de negocio, y e ir poco a poco acercando al usuario.
Todo esto lo expliqué en el post que puse en el Telegram.

**Comment by RubenDelgadoPareja** [comment]
He modificado los Milestones y añadido bastante más contenido en cada descripción. En cuanto esté correcto cierro este issue

**Comment by JJ** [comment]
Hazlo también en la documentación.
