### ISSUE TITLE
Formular los milestones como productos mínimamente viables

### ISSUE THREAD

**Issue by JJ** [RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica#28]
Lo esencial de un milestone es que contengan un entregable y un criterio de viabilidad. En ese sentido, no son un conjunto de tareas, porque las tareas no tienen ningún criterio para discernir si el resultado es viable o no. En el caso del [milestone 0](https://github.com/RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica/milestone/1), por ejemplo, debes decir qué debe ser capaz de hacer el repositorio para que se considere terminado (compilar el latex, corrección ortográfica) o qué debe incluir o cómo el capítulo (debe incluir todos los milestones iniciales, que también estarán en el repositorio), por ejemplo.

**Comment by RubenDelgadoPareja** [comment]
Cerrada en PR #23
