### ISSUE TITLE
El milestone 0 debe incluir el comprobador de la documentación

### ISSUE THREAD

**Issue by JJ** [RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica#29]
En desarrollo ágil la calidad es la primera preocupación, y #13 necesita que la memoria no tenga ningún tipo de error ortográfico. Hay que implementar 3 comprobadores
* Que la documentación compila correctamente
* Que no tienen errores ortográficos
* Si es posible, añadir también un comprobador gramatical.

Es conveniente que esto se haga incluso antes de empezar a escribir la memoria, para que no haya errores ortográficos que se tengan que corregir más adelante.

**Comment by RubenDelgadoPareja** [comment]
Cerrados en PR #26 y #30
