### ISSUE TITLE
Crear un mapa contextual del dominio del problema

### ISSUE THREAD

**Issue by RubenDelgadoPareja** [RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica#32]
El problema que se plantea al aplicar Diseño Dirigido por el Dominio:
Existen muchos subdominios adyacentes o dependientes del dominio del problema por lo que debemos, mediante el uso de un mapa contextual, dividir este entramado de dominios en diferentes contextos relacionados entre sí. De este modo dividiremos el problema en pequeños contextos más fáciles de manejar y poder centrarnos en lo verdaderamente importante.
Está relacionado con la HU https://github.com/RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica/issues/13 ya que es necesario para diseñar el producto y debe de reflejarse en al documentación

**Comment by JJ** [comment]
Todos los issues deben 
1. Plantear un problema
2. Estar relacionados con una HU.

**Comment by RubenDelgadoPareja** [comment]
Cerrado en el PR #40

**Comment by JJ** [comment]
Tienes que cerrarlos desde el "subject" del PR o desde un commit. Por favor, no hagas esto porque si no no está claro qué es realmente lo que se ha hecho para cerrarlo.

**Comment by JJ** [comment]
No entiendo muy bien por qué trabajas sobre develop de todas formas. Si lo que haces es cerrar cuando fusionas a develop, entonces develop es main, y la puedes poner como rama por omisión.

**Comment by RubenDelgadoPareja** [comment]
> Tienes que cerrarlos desde el "subject" del PR o desde un commit. Por favor, no hagas esto porque si no no está claro qué es realmente lo que se ha hecho para cerrarlo.

Lo acabo de cerrar así porque con el PR no se ha cerrado , está puesto en la descripción del PR #40 que cierra esta issue. 
En los próximos PR lo pondré en el commit para que funcione correctamente.
