### ISSUE TITLE
Crear un modelo del dominio del problema usando UML 

### ISSUE THREAD

**Issue by RubenDelgadoPareja** [RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica#34]
No existe ningún diagrama en concreto para crear el modelo del dominio del problema, por lo que usaré un diagrama de clases.
Dentro de este modelo debemos especificar los objetos del dominio los cuales pueden ser **Entidades** o **Objetos de valor**
Después de conocer todos los objetos debemos concretar las **Asociaciones** entre los objetos. 
En los modelos de dominios complejos pueden existir **Agregaciones o Agrupaciones** son un objeto que está formado por un conjunto de Entidades o Objetos de valor
Además hay que tener en cuenta que no toda la información o objetos se puede almacenar de manera persistente, de forma que debemos definir una capa o **Repositorio** que se encargue de esto. 
Finalmente tenemos que concretar los diferentes **Servicios de aplicaciones** que será la lógica que permite al proyecto funcionar
Está relacionado con la HU #13 ya que es necesario para diseñar el producto y debe de reflejarse en al documentación

**Comment by JJ** [comment]
¿UML? ¿Quién ha pedido eso y para qué sirve?
UML no te resuelve absolutamente nada. Si quieres modelizar el problema, usa domain driven design.
