### ISSUE TITLE
[HU] Como sanitario necesito establecer el riesgo a un usuario

### ISSUE THREAD

**Issue by RubenDelgadoPareja** [RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica#4]
-El sanitario debe establecer el riesgo de un usuario siguiendo su criterio profesional 
-El riesgo de cada usuario les otorgará mayor o menor prioridad en la lista de colas
-Incluimos en esta HU actualizar el riesgo de un paciente ya que pueden cambiar

**Comment by RubenDelgadoPareja** [comment]
[Tarea 3.1]: Comprobamos que el usuario tiene un registro médico asociado 
[Tarea 3.2]: Permitir al sanitario establecer el riesgo 
[Tarea 3.3]: Permitir modificar el registro después de una cita con el paciente
[Tarea 3.4]: Comprobar que la actualización es correcta y el paciente ha tenido una cita 
[Tarea 3.5]: Permitir  recalcular la prioridad de un paciente
[Tarea 3.6]: Comprobamos que el usuario tiene un registro médico asociado y ha tenido un cita recientemente
[Tarea 3.7]: Permitir al sanitario actualizar el riesgo de un paciente

**Comment by JJ** [comment]
Esto tampoco es una historia de usuario, es el contexto. Tienes que saber establecer el riesgo, y el triage inteligente te ayudará.
Deberías dejar de lado las cosas administrativas (que si es un paciente y qué cosa) para modelizar el problema. ¿Dado el contexto, cómo puedes hacer el triage "inteligente"?

**Comment by RubenDelgadoPareja** [comment]
Esta HU es redundante debido a la siguiente #5
