### ISSUE TITLE
Añadir framework de prueba al proyecto para mejorar la calidad del código

### ISSUE THREAD

**Issue by RubenDelgadoPareja** [RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica#47]
Necesario para la #13 para comprobar en todo momento que el código es correcto.
Esta issue se completará cuando se instale la herramienta de testeo y funcione correctamente. 
El desarrollo de los test irán incluidos en otras issues.

**Comment by JJ** [comment]
Un modelo no necesita tests de código, porque apenas tiene código más allá de estructuras de datos (que se pueden analizar simplemente con analizadores estáticos). Una vez más, conviene que organices un poco el desarrollo para no ir haciendo tareas que más adelante tengas que rehacer o deshacer.
