### ISSUE TITLE
Configurar el corrector de ortográfico y semántico 

### ISSUE THREAD

**Issue by RubenDelgadoPareja** [RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica#53]
Para que la documentación se complete sin errores es primordial que antes de cada commit, comprobemos que toda la ortografía de los nuevos cambios son correctos. Por lo que es necesario para la HU #13 y la documentación.

**Comment by JJ** [comment]
Este issue no tiene nada que ver con el modelado del problema, sería infraestructura inicial, que deberías haber incluido como milestone 0.
