### ISSUE TITLE
Modelar el paciente sobre el triage inteligente

### ISSUE THREAD

**Issue by RubenDelgadoPareja** [RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica#58]
Esta issue resuelve el problema de abstraer al paciente del dominio del problema y plasmarlo en el sistema representado todas las características de este necesario para el triage inteligente.
Voy a crear los archivos necesario para crear el modelo de Paciente, deben ir incluidos todos las Entidades y Objetos de Valor que contenga. Esta issue se completará cuando quede el modelo Paciente creado y acotado correctamente y es necesaria para el desarrollo de todo el conjunto del modelo del negocio #36.

**Comment by JJ** [comment]
Los issues siempre son problemas. No pueden ser "agregar X", porque cualquier cosa que sea X lo solucionaría. Y una vez más, deben estar relacionados con una HU. Si no plantean los problemas que hay presentes en la HU, pueden acabar en código innecesario o en todo caso imposible de evaluar porque al no resolver ningún problema es imposible decir si lo hacen bien o no.
