### ISSUE TITLE
Construir la infraestructura inicial

### ISSUE THREAD

**Issue by RubenDelgadoPareja** [RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica#59]
Esta tarea consistirá en:

1. Instalar Node.js en el sistema con nvm e ir agregando paquetes
2. Agregar typescript, ESlinter y Prettier para la compilación y tener código de calidad
3. Agregar un workflow para ejecutar el linter antes de cada push
4. Plasmar las tareas en la documentación y las decisiones tomadas justificadas
Esta tarea es necesaria para poder comenzar a crear el Modelo correctamente con código de calidad.
Esta issue engloba las tareas #46 y #47 que han quedado obsoletas debido a cambios en el proyecto
La PR que añade a la documentación el uso de estas tecnologías y su razonamiento en la #13

**Comment by JJ** [comment]
Los issues nunca son tareas, son problemas. 
También deben siempre estar relacionados con una HU. En este caso es difícil saber qué, pero si se trata de infraestructura será probablemente #13
