### ISSUE TITLE
Como administrador necesito una plataforma o apartado para mantener y adaptar el sistema 

### ISSUE THREAD

**Issue by RubenDelgadoPareja** [RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica#6]
-Debe de existir alguna forma de poder acceder al sistema de colas, con la intención de que la heurística vaya evolucionando junto con la app

**Comment by JJ** [comment]
Las tareas las puedes meter en el propio cuerpo del issue, usando `* [ ]`. Pero es mejor que crees issues independientes, y que esos issues se asignen a milestones.
Recuerda que las HUs siempre están en el dominio del problema. Los que hagan referencia a implementación nunca pueden ser HUs.

**Comment by RubenDelgadoPareja** [comment]
He reformulado esta HU para que exprese realmente lo que un administrador de la aplicación necesita para mantener el sistema

**Comment by JJ** [comment]
> Esto es lo que tú necesitas que haga el administrador. El administrador no es cliente, porque no obtiene ningún beneficio del mismo, y si lo es, tienes que poner en la HU cuál es el beneficio que obtiene de la misma ("ver" no es uno)

Te reitero esto. Podría ser un issue, pero tendrás que establecer qué es lo que necesita el administrador y qué nivel va a ser cliente de la aplicación.
