### ISSUE TITLE
Modelado del dominio del problema: Contexto del Paciente (Entidad y Value Objects)

### ISSUE THREAD

**Issue by RubenDelgadoPareja** [RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica#71]
Como dice la HU: "Como paciente quiero tener prioridad en el orden de citas médicas".
Para cumplir con esta historia debemos poder reflejar la lógica del negocio del problema sobre el sistema.
Inicialmente necesitamos modelar a la entidad del Paciente para poder realizar la acción. 
En DDD se traduce a tener un contexto de Paciente, el cual representa la lógica que conlleva el propio Paciente. #19

**Comment by JJ** [comment]
En estso issues deberías ser un poco más explícito, añadir un poco de contexto extraído de las historias de usuario. ¿Crees que con la información que hay en el issue se puede modelar? Esencialmente, sólo sabes que se trata de algo llamado Paciente.
