### ISSUE TITLE
Modelado del dominio del problema: Contexto de la Cita (Entidad y Value Objects)

### ISSUE THREAD

**Issue by RubenDelgadoPareja** [RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica#72]
Como dice la HU: "Como paciente quiero tener prioridad en el orden de citas médicas".
Para cumplir con esta historia debemos poder reflejar la lógica del negocio del problema sobre el sistema.
Inicialmente necesitamos modelar y diseñar la Cita. 
En DDD se traduce a tener un contexto de Cita , el cual representa la lógica que conlleva pedir una Cita. #19 

- [x] #90

**Comment by JJ** [comment]
Lo que DDD diga es algo que debe añadirse como comentario en el commit. Un issue sólo plantea problemas.
