### ISSUE TITLE
Pruebas Unitarias del modulo de Paciente

### ISSUE THREAD

**Issue by RubenDelgadoPareja** [RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica#81]
Durante el desarrollo del modulo de Paciente #74 ha surgido el problema de que la clase de Paciente debe funcionar correctamente. 
Se comprobará mediante unos Test Unitarios. Debemos de haber cerrado con anterioridad la issue #74.
Este problema hace referencia a la HU #19 , ya que, es necesario que el paciente funcione correctamente para pedir una cita.
Además aporta calidad y robustez al código que contribuye a solucionar #13 
La rama y PR que tiene asociada deja de tener sentido, se ha destinado a la configuración de las herramientas de testeo
Esta issue no se podrá completar hasta que no tengamos métodos en el modulo de Cita a testear...

**Comment by JJ** [comment]
Los issues deben plantear problemas, no tareas. "Pruebas unitarias" no es evaluable: cualquier prueba unitaria lo cerraría. Si estás trabajando con una historia de usuario, debe desarrollar la misma para dejar claro qué es lo qu ese está tratando de solucionar de esa historia de usuario.
