### ISSUE TITLE
Estructura de datos de una Cita, a partir de su modelo

### ISSUE THREAD

**Issue by RubenDelgadoPareja** [RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica#88]
En relación con la HU #19 , no podemos priorizar una cita sin poder crearla y guardarla en base de datos. 
Para ello debemos definir la estructura de datos de una cita y completar el flujo de creación. Una vez completemos esto podremos pensar en cómo priorizar la cita.
Para poder comenzar con esta issue debemos haber completado #85 y #86

**Comment by JJ** [comment]
Los issues son problemas y no contienen detalles de implementación como "guardarla en una base de datos". El que se puede guardar o no no parece tampoco un problema.
"Como priorizar la cita" es el problema que hay que resolver en esta estructura de datos, modelizando el dominio del problema (siguiendo DDD o cualquier otra metodología). Tal como está expresado, cualquier estructura de datos puede resolver este issue, sin ningún avance hacia la resolución del problema.
