### ISSUE TITLE
Análisis del modelado de cita - Atributos de una Cita

### ISSUE THREAD

**Issue by RubenDelgadoPareja** [RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica#91]
Esta issue surge de la #90, para completar el análisis del modelado debemos definir las características que tiene una Cita , razonando el valor que aportan al usuario. 

En esta issue se definirán los atributos de una Cita. Estos atributos se traducirán al código como objetos de valor de la cita.
Principalmente una cita debe tener un identificador para distinguirla del resto.
La característica más importante de la cita es la fecha, tanto día como hora.
Una cita siempre tiene que tener un paciente y o médico asociado (El médico no siempre es necesario).
La cita puede ser de diferente tipo: Presencial o telefónica.
Posiblemente puedan aparecer más objetos de valor.

- [ ] Código

**Comment by RubenDelgadoPareja** [comment]
En esta issue se definirán los atributos de una Cita. Estos atributos se traducirán al código como objetos de valor de la cita. 
Principalmente una cita debe tener un identificador para distinguirla del resto. 
La característica más importante de la cita es la fecha, tanto día como hora. 
Una cita siempre tiene que tener un paciente y o médico asociado (El médico no siempre es necesario).
La cita puede ser de diferente tipo: Presencial o telefónica. 
Posiblemente puedan aparecer más objetos de valor.

**Comment by JJ** [comment]
¿Te parece que "posiblemente puedan aparecer más objetos de valor" es un enunciado preciso de un problema?
Permíteme que te insista en que los issues deben enunciar un problema que surja de una historia de usuario. En este caso debe tratarse de #4, pero deberías enunciarlo explícitamente. Si no lo haces, puedes acabar con características excesivas que no sirven a la historia de usuario. En concreto, no parece que ninguno de los commits que se han hecho contra este issue resuelvan el problema enunciado en la HU
