### ISSUE TITLE
Análisis del modelo de Paciente

### ISSUE THREAD

**Issue by RubenDelgadoPareja** [RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica#97]
Después de comenzar la issue https://github.com/RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica/issues/71 surge el problema de definir las posibles características que define un paciente, las restricciones que puede tener a la hora de darse de alta o de baja, las relaciones con el resto del dominio. Esta issue es imprescindible para la HU https://github.com/RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica/issues/19, sin un modelo correcto de Paciente nunca podrá pedir la cita.

Por lo que debemos de hacer un estudio inicial sobre las historias de usuario y user journeys para poder representar este concepto lo más fiel posible al dominino

**Comment by JJ** [comment]
Un issue no define la solución, define el problema. Si defines la solución, el trabajo está hecho en el issue, no en el código. En la cadena de issues, este hace referencia a la HU #19 (que también habría que perfilar), pero dado que es así, ¿qué tiene que ver el género o el número de teléfono con la prioridad en la cita médica?
